services:
  trans_it-api-container:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASS: root
      DB_HOST: mysql-db-container
      DB_NAME: trans_it_db
      JWT_SECRET: secret
      JWT_EXPIRATION: 86400
      JWT_APP_NAME: trans-it
    depends_on:
      - mysql-db-container
    networks:
      - trans_it-net

  mysql-db-container:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trans_it_db
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - trans_it-net

networks:
  trans_it-net:
    driver: bridge

volumes:
  mysql-data: